@{ Tweaks = @(
@{Id='ClassicContextMenu';Category='Interface';Title='Classic Context Menu';Description="Restores the Windows 10 right-click menu";Provider='RegistryKey';Reversible=$true;Restart='Explorer';Operations=@(@{Path='HKCU:\Software\Classes\CLSID\{86ca1aa0-34aa-4e8b-a509-50c905bae2a2}\InprocServer32'})},
@{Id='DisableBingSearch';Category='Interface';Title='Disable Bing in Start Menu';Description='Prevents Start from querying Bing';Provider='Registry';Reversible=$true;Restart='Explorer';Operations=@(@{Path='HKCU:\Software\Microsoft\Windows\CurrentVersion\Search';Name='BingSearchEnabled';Type='DWord';Value=0})},
@{Id='DisableWidgets';Category='Interface';Title='Disable Taskbar Widgets';Description='Hides the taskbar widgets button';Provider='Registry';Reversible=$true;Restart='Explorer';Operations=@(@{Path='HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced';Name='TaskbarDa';Type='DWord';Value=0})},
@{Id='DisableCopilot';Category='Interface';Title='Disable Windows Copilot AI';Description='Disables Copilot at user and machine policy level';Provider='Registry';Reversible=$true;Restart='Explorer';Operations=@(@{Path='HKCU:\Software\Policies\Microsoft\Windows\WindowsCopilot';Name='TurnOffWindowsCopilot';Type='DWord';Value=1},@{Path='HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsCopilot';Name='TurnOffWindowsCopilot';Type='DWord';Value=1})},
@{Id='DisableEdgeBackground';Category='Interface';Title='Disable MS Edge Background Tasks';Description='Disables Edge background mode and sidebar';Provider='Registry';Reversible=$true;Restart='None';Operations=@(@{Path='HKLM:\SOFTWARE\Policies\Microsoft\Edge';Name='BackgroundModeEnabled';Type='DWord';Value=0},@{Path='HKLM:\SOFTWARE\Policies\Microsoft\Edge';Name='HubsSidebarEnabled';Type='DWord';Value=0})},
@{Id='DisableAdsAndTips';Category='Interface';Title='Disable Recommendations, Tips & Ads';Description='Disables Windows content suggestions';Provider='Registry';Reversible=$true;Restart='Explorer';Operations=@(@{Path='HKCU:\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager';Name='SubscribedContent-338389Enabled';Type='DWord';Value=0},@{Path='HKCU:\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager';Name='SubscribedContent-353694Enabled';Type='DWord';Value=0},@{Path='HKCU:\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager';Name='SubscribedContent-353696Enabled';Type='DWord';Value=0})},
@{Id='MenuShowDelayZero';Category='Interface';Title='Instant Sub-Menu Popup (0ms)';Description='Removes submenu hover delay';Provider='Registry';Reversible=$true;Restart='Explorer';Operations=@(@{Path='HKCU:\Control Panel\Desktop';Name='MenuShowDelay';Type='String';Value='0'})},
@{Id='DisableTaskbarAnimations';Category='Interface';Title='Disable Taskbar Animations';Description='Disables taskbar animations';Provider='Registry';Reversible=$true;Restart='Explorer';Operations=@(@{Path='HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced';Name='TaskbarAnimations';Type='DWord';Value=0})}
)}